# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OS47DHsTCeggcZDRDcE9W9ey8s1O7F9v
"""

import pandas as pd
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

stu=pd.read_csv("/content/Students Social Media Addiction.csv")

df=pd.DataFrame(stu)

df

lable=LabelEncoder()
cat_cols=['Gender','Academic_Level','Country','Most_Used_Platform','Relationship_Status','Affects_Academic_Performance']

for col in cat_cols:
  df[col]=lable.fit_transform(df[col])
df.head()

df_encoded=pd.get_dummies(df,columns=cat_cols,drop_first=True)
df_encoded.head()

df_encoded



